# Generated by Django 4.2 on 2023-04-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('保单跟进', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name_plural': '投保信息'},
        ),
    ]
