# Generated by Django 4.2 on 2023-04-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('保单管理', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom3',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custom3',
            name='投保时间',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='custom3',
            name='邮箱',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
