# Generated by Django 4.2 on 2023-04-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('保单管理', '0002_custom3_id_alter_custom3_投保时间_alter_custom3_邮箱'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom3',
            options={'verbose_name_plural': '保单信息'},
        ),
        migrations.AlterField(
            model_name='custom3',
            name='投保时间',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='custom3',
            name='邮箱',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
