# Generated by Django 4.2 on 2023-04-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('保单管理', '0003_alter_custom3_options_alter_custom3_投保时间_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom3',
            options={'verbose_name_plural': '在线投保'},
        ),
    ]
