# Generated by Django 4.2 on 2023-05-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('保单管理', '0005_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='custom3',
        ),
    ]
