# Generated by Django 4.2 on 2023-05-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('保单管理', '0007_custom3_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom3',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=32, null=True, verbose_name='性别'),
        ),
    ]
