# Generated by Django 4.2 on 2023-05-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('保单管理', '0008_custom3_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom3',
            name='性别',
        ),
    ]
