# Generated by Django 4.2 on 2023-05-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('保单管理', '0009_remove_custom3_性别'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom3',
            name='sex1',
            field=models.CharField(blank=True, choices=[('1', '全家保'), ('2', '吉祥保'), ('3', '女神保'), ('4', '男神保'), ('5', '育才保'), ('6', '孝心保')], max_length=32, null=True, verbose_name='投保类型'),
        ),
    ]
