# Generated by Django 4.2 on 2023-04-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('产品管理', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='产品介绍')),
            ],
            options={
                'verbose_name_plural': '产品2',
            },
        ),
        migrations.CreateModel(
            name='TestModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='产品介绍')),
            ],
            options={
                'verbose_name_plural': '产品3',
            },
        ),
        migrations.AlterModelOptions(
            name='testmodel',
            options={'verbose_name_plural': '产品1'},
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='content',
            field=models.TextField(verbose_name='产品介绍'),
        ),
    ]
