# Generated by Django 4.2 on 2023-05-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('产品管理', '0002_testmodel2_testmodel3_alter_testmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='产品介绍')),
            ],
            options={
                'verbose_name_plural': '产品4',
            },
        ),
        migrations.CreateModel(
            name='TestModel5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='产品介绍')),
            ],
            options={
                'verbose_name_plural': '产品5',
            },
        ),
        migrations.CreateModel(
            name='TestModel6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='产品介绍')),
            ],
            options={
                'verbose_name_plural': '产品6',
            },
        ),
    ]
