# Generated by Django 4.2 on 2023-04-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('咨询', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
