# Generated by Django 4.2 on 2023-04-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('咨询', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('客户提问', models.CharField(blank=True, max_length=200, null=True)),
                ('业务员解答', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '咨询列表',
            },
        ),
    ]
