# Generated by Django 4.2 on 2023-04-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('咨询', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('客户提问', models.CharField(blank=True, max_length=200, null=True)),
                ('备注', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '业务员解答 ',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '客户提问 '},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='业务员解答',
            new_name='备注',
        ),
    ]
