# Generated by Django 4.2 on 2023-04-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('咨询', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user1',
            new_name='custom',
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='custom1',
        ),
        migrations.AlterModelOptions(
            name='custom',
            options={'verbose_name_plural': '客户提问 '},
        ),
        migrations.AlterModelOptions(
            name='custom1',
            options={'verbose_name_plural': '业务员解答 '},
        ),
        migrations.RenameField(
            model_name='custom',
            old_name='业务员解答',
            new_name='客户提问',
        ),
        migrations.RenameField(
            model_name='custom1',
            old_name='客户提问',
            new_name='业务员解答',
        ),
    ]
