# Generated by Django 4.2 on 2023-04-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('咨询', '0007_rename_user1_custom_rename_user_custom1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='custom',
        ),
        migrations.DeleteModel(
            name='custom1',
        ),
    ]
