# Generated by Django 4.2 on 2023-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('咨询', '0008_delete_custom_delete_custom1'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('客户提问', models.CharField(blank=True, max_length=200, null=True)),
                ('备注', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '客户提问 ',
            },
        ),
        migrations.CreateModel(
            name='custom1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('业务员解答', models.CharField(blank=True, max_length=200, null=True)),
                ('备注', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '业务员解答 ',
            },
        ),
    ]
