# Generated by Django 4.2 on 2023-04-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('咨询', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='咨询号',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='custom1',
            name='咨询号',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
