# Generated by Django 4.2 on 2023-04-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('文件管理', '0002_article_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
