# Generated by Django 4.2 on 2023-04-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('文件管理', '0003_file_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('ph', models.ImageField(upload_to='uploadImages', verbose_name='图片')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.DeleteModel(
            name='file',
        ),
    ]
