# Generated by Django 4.2 on 2023-04-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('文件管理', '0004_article_delete_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文件上传'},
        ),
    ]
