# Generated by Django 4.2 on 2023-04-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('通知', '0002_alter_notice_options_remove_notice_content_notice_通知'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='通知',
        ),
        migrations.AddField(
            model_name='notice',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='通知'),
        ),
    ]
